# Generated by Django 5.2.16 on 2026-08-09 03:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministratorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrollment_required", "Enrollment required"),
                            ("active", "Active"),
                            ("recovery_required", "Recovery required"),
                            ("disabled", "Disabled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdministratorSecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("denied", "Denied"),
                            ("unavailable", "Unavailable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_events",
                        to="identity.administratorprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrator_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdministratorSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_key", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("authenticated_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_verified_at", models.DateTimeField(blank=True, null=True)),
                ("fresh_verified_at", models.DateTimeField(blank=True, null=True)),
                ("absolute_expires_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("device_label", models.CharField(max_length=160)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("recovery_restricted", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrator_sessions",
                        to="identity.administratorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdministratorTOTPDevice",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of this device.", max_length=64
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=True, help_text="Is this device ready for use?"),
                ),
                (
                    "throttling_failure_timestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text=(
                            "A timestamp of the last failed verification attempt. "
                            "Null if last attempt succeeded."
                        ),
                        null=True,
                    ),
                ),
                (
                    "throttling_failure_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successive failed attempts."
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("seed_envelope", models.JSONField()),
                ("digits", models.PositiveSmallIntegerField(default=6, editable=False)),
                ("step", models.PositiveSmallIntegerField(default=30, editable=False)),
                ("drift", models.SmallIntegerField(default=0)),
                ("last_t", models.BigIntegerField(default=-1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("replaced_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="totp_devices",
                        to="identity.administratorprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrator_totp_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("batch_id", models.UUIDField()),
                ("public_id", models.CharField(max_length=8, unique=True)),
                ("encoded_secret", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_codes",
                        to="identity.administratorprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="administratorprofile",
            constraint=models.UniqueConstraint(
                models.Value(1),
                condition=models.Q(("status", "disabled"), _negated=True),
                name="identity_one_enabled_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="administratorsecurityevent",
            index=models.Index(
                fields=["profile", "-created_at", "-id"], name="identity_event_owner_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="administratorsecurityevent",
            index=models.Index(fields=["action", "-created_at"], name="identity_event_action_idx"),
        ),
        migrations.AddIndex(
            model_name="administratorsession",
            index=models.Index(
                fields=["profile", "revoked_at", "absolute_expires_at"],
                name="identity_session_owner_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="administratorsession",
            index=models.Index(
                fields=["expires_at", "revoked_at"], name="identity_session_expiry_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="administratortotpdevice",
            constraint=models.CheckConstraint(
                condition=models.Q(("digits", 6)), name="identity_totp_six_digits"
            ),
        ),
        migrations.AddConstraint(
            model_name="administratortotpdevice",
            constraint=models.CheckConstraint(
                condition=models.Q(("step", 30)), name="identity_totp_thirty_seconds"
            ),
        ),
        migrations.AddIndex(
            model_name="recoverycode",
            index=models.Index(
                fields=["profile", "batch_id", "consumed_at"], name="identity_recovery_batch_idx"
            ),
        ),
    ]
