# Generated by Django 5.2.16 on 2026-08-30 17:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("launchloop", "0002_demoactor_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("month", models.DateField(unique=True)),
                ("limit_microusd", models.PositiveBigIntegerField()),
                ("reserved_microusd", models.PositiveBigIntegerField(default=0)),
                ("settled_microusd", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reserved_microusd__gte", 0)),
                        name="agents_period_reserved_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("settled_microusd__gte", 0)),
                        name="agents_period_settled_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("profile_id", models.SlugField(max_length=64)),
                ("revision", models.PositiveIntegerField()),
                (
                    "provider",
                    models.CharField(
                        choices=[("hermes", "Hermes"), ("groq", "Groq"), ("openai", "OpenAI")],
                        max_length=16,
                    ),
                ),
                ("model", models.CharField(max_length=120)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("workflow", "Workflow"),
                            ("evaluation_judge", "Evaluation judge"),
                            ("fallback", "Fallback"),
                        ],
                        max_length=24,
                    ),
                ),
                ("max_input_tokens", models.PositiveIntegerField()),
                ("max_output_tokens", models.PositiveIntegerField()),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=3)),
                ("input_price_microusd_per_million", models.PositiveBigIntegerField(null=True)),
                ("output_price_microusd_per_million", models.PositiveBigIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile_id", "revision"),
                        name="agents_unique_model_profile_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_input_tokens__gt", 0)),
                        name="agents_profile_input_tokens_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_output_tokens__gt", 0)),
                        name="agents_profile_output_tokens_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policy_id", models.SlugField(max_length=64)),
                ("revision", models.PositiveIntegerField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("workflow", "Workflow"),
                            ("evaluation_judge", "Evaluation judge"),
                            ("fallback", "Fallback"),
                        ],
                        max_length=24,
                    ),
                ),
                ("per_run_limit_microusd", models.PositiveBigIntegerField(default=500000)),
                ("monthly_limit_microusd", models.PositiveBigIntegerField(default=25000000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.modelprofile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BudgetReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("run_id", models.UUIDField(unique=True)),
                ("estimated_input_tokens", models.PositiveIntegerField()),
                ("estimated_output_tokens", models.PositiveIntegerField()),
                ("reserved_cost_microusd", models.PositiveBigIntegerField()),
                ("settled_input_tokens", models.PositiveIntegerField(null=True)),
                ("settled_output_tokens", models.PositiveIntegerField(null=True)),
                ("settled_cost_microusd", models.PositiveBigIntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("settled", "Settled"),
                            ("released", "Released"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.budgetperiod"
                    ),
                ),
                (
                    "model_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.modelprofile"
                    ),
                ),
                (
                    "routing_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.routingpolicy"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("package_hash", models.CharField(max_length=64)),
                ("fixture_manifest_id", models.SlugField(max_length=64)),
                ("fixture_manifest_revision", models.PositiveIntegerField()),
                ("fixture_manifest_digest", models.CharField(max_length=64)),
                (
                    "privacy_mode",
                    models.CharField(
                        choices=[
                            ("synthetic_full", "Synthetic full"),
                            ("pilot_minimized", "Pilot minimized"),
                            ("disabled", "Disabled"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("budget_exhausted", "Budget exhausted"),
                            ("cancelled", "Cancelled"),
                            ("dependency_unavailable", "Dependency unavailable"),
                            ("invalid_output", "Invalid output"),
                            ("provider_unavailable", "Provider unavailable"),
                            ("timeout", "Timeout"),
                        ],
                        max_length=32,
                    ),
                ),
                ("trace_id", models.CharField(max_length=32)),
                ("span_count", models.PositiveSmallIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cost_microusd", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.eventrevision"
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_runs",
                        to="launchloop.workflow",
                    ),
                ),
                (
                    "model_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.modelprofile"
                    ),
                ),
                (
                    "routing_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.routingpolicy"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("model_inference", "Model inference"),
                            ("tool_call", "Tool call"),
                            ("validation", "Validation"),
                            ("repair", "Repair"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("input_summary", models.CharField(blank=True, max_length=500)),
                ("output_summary", models.CharField(blank=True, max_length=500)),
                (
                    "failure_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_output", "Invalid output"),
                            ("provider_unavailable", "Provider unavailable"),
                            ("timeout", "Timeout"),
                            ("tool_denied", "Tool denied"),
                            ("tool_error", "Tool error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="agents.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "sequence"), name="agents_unique_run_step_sequence"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1), ("sequence__lte", 1000)),
                        name="agents_step_sequence_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("duration_ms__lte", 3600000)),
                        name="agents_step_duration_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BudgetLedgerRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("run_id", models.UUIDField()),
                ("model_profile_id_snapshot", models.SlugField(max_length=64)),
                ("model_profile_revision", models.PositiveIntegerField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("settled", "Settled"),
                            ("released", "Released"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cost_microusd", models.PositiveBigIntegerField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_records",
                        to="agents.budgetreservation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "entry_type"), name="agents_unique_run_ledger_entry_type"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cost_microusd__gte", 0)),
                        name="agents_ledger_cost_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "USD")), name="agents_ledger_currency_usd"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="routingpolicy",
            constraint=models.UniqueConstraint(
                fields=("policy_id", "revision"), name="agents_unique_routing_policy_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="routingpolicy",
            constraint=models.UniqueConstraint(
                fields=("model_profile",), name="agents_one_policy_per_profile_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="routingpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("per_run_limit_microusd__gt", 0)),
                name="agents_policy_run_limit_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_limit_microusd__gt", 0)),
                name="agents_policy_month_limit_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_cost_microusd__gte", 0)),
                name="agents_reservation_cost_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt__gte", 1), ("attempt__lte", 10)),
                name="agents_run_attempt_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("span_count__lte", 1000)), name="agents_run_span_count_range"
            ),
        ),
    ]
