# Generated by Django 5.2.17 on 2026-09-22 02:06

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_fixed_openai_judge_profile_r2"),
        ("launchloop", "0005_providerevent_local_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowCapability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("revision_digest", models.CharField(max_length=64)),
                ("tools", models.JSONField()),
                ("audience", models.CharField(default="civicloop-hermes", max_length=32)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                ("correlation_id", models.UUIDField(null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.demoactor"
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.eventrevision"
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.workflow"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCPSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("content", models.JSONField()),
                ("digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.workflowcapability"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCPInvocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("idempotency_digest", models.CharField(max_length=64, unique=True)),
                ("argument_digest", models.CharField(max_length=64)),
                ("tool_name", models.CharField(max_length=40)),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.workflowcapability"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=16)),
                ("operation_kind", models.CharField(max_length=40)),
                ("action_digest", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("receipt", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.demoactor"
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="launchloop.approvalrequest",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.eventrevision"
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.workflow"
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.mcpsubmission"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("approval__isnull", True),
                            ("receipt__isnull", True),
                            ("status", "pending"),
                        ),
                        name="agents_broker_pending_only",
                    )
                ],
            },
        ),
    ]
