# Generated by Django 5.2.17 on 2026-09-26 17:32

import uuid

import django.db.models.deletion
from django.db import migrations, models

FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION agents_reject_hermes_evidence_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Hermes run evidence is immutable.' USING ERRCODE = '55000';
END;
$$;
"""

EVIDENCE_TRIGGERS = {
    "agents_run_event_immutable": "agents_agentrunevent",
    "agents_hermes_binding_immutable": "agents_hermesrunbinding",
}


def create_evidence_triggers(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(FUNCTION_SQL)
    for trigger, table in EVIDENCE_TRIGGERS.items():
        schema_editor.execute(
            f"""CREATE TRIGGER {trigger} BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION agents_reject_hermes_evidence_mutation();"""
        )


def drop_evidence_triggers(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    for trigger, table in EVIDENCE_TRIGGERS.items():
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table};")
    schema_editor.execute("DROP FUNCTION IF EXISTS agents_reject_hermes_evidence_mutation();")


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_mcp_broker"),
        ("launchloop", "0005_providerevent_local_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRunControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cancel_requested_at", models.DateTimeField(null=True)),
                ("admission_disabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control",
                        to="agents.agentrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HermesRunBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("revision_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.demoactor"
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hermes_binding",
                        to="agents.agentrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentRunEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("event_type", models.CharField(max_length=32)),
                ("outcome", models.CharField(max_length=32)),
                ("detail_digest", models.CharField(max_length=64)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="agents.agentrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "sequence"), name="agents_run_event_sequence"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="agents_run_event_sequence_positive",
                    ),
                ],
            },
        ),
        migrations.RunPython(create_evidence_triggers, reverse_code=drop_evidence_triggers),
    ]
