# Generated by Django 5.2.17 on 2026-09-26 17:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_mcp_broker"),
        ("launchloop", "0005_providerevent_local_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRunControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cancel_requested_at", models.DateTimeField(null=True)),
                ("admission_disabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control",
                        to="agents.agentrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HermesRunBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("revision_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.demoactor"
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hermes_binding",
                        to="agents.agentrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentRunEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("event_type", models.CharField(max_length=32)),
                ("outcome", models.CharField(max_length=32)),
                ("detail_digest", models.CharField(max_length=64)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="agents.agentrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "sequence"), name="agents_run_event_sequence"
                    )
                ],
            },
        ),
    ]
