# Generated by Django 5.2.17 on 2026-10-10 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_hermes_worker_trace_context"),
        ("identity", "0002_security_event_append_only"),
        ("launchloop", "0005_providerevent_local_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="hermesrunbinding",
            name="owner_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="identity.administratorsession",
            ),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="fixture_manifest_digest",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="fixture_manifest_id",
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="agentrun",
            name="fixture_manifest_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hermes_lane", False),
                    models.Q(
                        ("fixture_manifest_digest__isnull", False),
                        ("fixture_manifest_id__isnull", False),
                        ("fixture_manifest_revision__isnull", False),
                        ("privacy_mode", "synthetic_full"),
                    ),
                    models.Q(
                        ("fixture_manifest_digest__isnull", True),
                        ("fixture_manifest_id__isnull", True),
                        ("fixture_manifest_revision__isnull", True),
                        ("privacy_mode", "pilot_minimized"),
                    ),
                    _connector="OR",
                ),
                name="agents_hermes_fixture_provenance",
            ),
        ),
    ]
