# Generated by Django 5.2.16 on 2026-08-30 17:40

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "evaluator",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic"),
                            ("llm_judge", "LLM judge"),
                            ("human_review", "Human review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("inconclusive", "Inconclusive"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("reason_codes", models.JSONField()),
                ("summary", models.CharField(max_length=1000)),
                ("dataset_id", models.SlugField(max_length=64)),
                ("dataset_version", models.PositiveIntegerField()),
                ("example_id", models.UUIDField()),
                ("prompt_reference", models.SlugField(max_length=64)),
                ("prompt_version", models.PositiveIntegerField()),
                ("evaluation_policy_id", models.SlugField(max_length=64)),
                ("evaluation_policy_version", models.PositiveIntegerField()),
                ("evaluated_schema_id", models.CharField(max_length=160)),
                ("evaluated_schema_version", models.CharField(max_length=32)),
                ("candidate_id", models.CharField(max_length=64)),
                ("candidate_version", models.PositiveIntegerField()),
                ("judge", models.JSONField(blank=True, default=dict)),
                ("rubric_id", models.CharField(max_length=64)),
                ("rubric_version", models.PositiveIntegerField()),
                ("deterministic_checks", models.JSONField()),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cost_microusd", models.PositiveBigIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("trace_id", models.CharField(max_length=32)),
                ("advisory_only", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agents.modelprofile",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_results",
                        to="agents.agentrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("advisory_only", True)),
                        name="evaluations_always_advisory",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("latency_ms__lte", 3600000)),
                        name="evaluations_latency_range",
                    ),
                ],
            },
        ),
    ]
