# ruff: noqa: E501
# Generated by Django 5.2.16 on 2026-08-16 00:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedSecret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("eventbrite", "Eventbrite"),
                            ("groq", "Groq"),
                            ("iterable", "Iterable"),
                            ("openai", "OpenAI"),
                        ],
                        max_length=32,
                    ),
                ),
                ("scope", models.CharField(max_length=64)),
                ("ciphertext", models.BinaryField()),
                ("nonce", models.BinaryField(max_length=12)),
                (
                    "algorithm",
                    models.CharField(default="AES-256-GCM", editable=False, max_length=32),
                ),
                ("key_id", models.CharField(editable=False, max_length=64)),
                ("envelope_version", models.PositiveSmallIntegerField(default=1, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("replaced_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_integration_secrets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disabled_integration_secrets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_integration_secrets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("eventbrite", "Eventbrite"),
                            ("groq", "Groq"),
                            ("iterable", "Iterable"),
                            ("openai", "OpenAI"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_configured", "Not configured"),
                            ("configured", "Configured"),
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("disabled", "Disabled"),
                        ],
                        default="not_configured",
                        max_length=32,
                    ),
                ),
                ("capabilities", models.JSONField(default=list)),
                ("configuration", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_successful_test_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_failure_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("authentication", "Authentication"),
                            ("authorization", "Authorization"),
                            ("rate_limit", "Rate limit"),
                            ("timeout", "Timeout"),
                            ("network", "Network"),
                            ("invalid_response", "Invalid response"),
                            ("provider_unavailable", "Provider unavailable"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connections",
                        to="integrations.encryptedsecret",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationHealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("healthy", "Healthy"), ("degraded", "Degraded")], max_length=16
                    ),
                ),
                (
                    "error_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("authentication", "Authentication"),
                            ("authorization", "Authorization"),
                            ("rate_limit", "Rate limit"),
                            ("timeout", "Timeout"),
                            ("network", "Network"),
                            ("invalid_response", "Invalid response"),
                            ("provider_unavailable", "Provider unavailable"),
                        ],
                        max_length=32,
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField()),
                ("correlation_id", models.UUIDField()),
                ("tested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_checks",
                        to="integrations.integrationconnection",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="encryptedsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider__in", ["eventbrite", "groq", "iterable", "openai"])),
                name="integrations_secret_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="encryptedsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "disabled"])),
                name="integrations_secret_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="encryptedsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="integrations_secret_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="encryptedsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(("algorithm", "AES-256-GCM")),
                name="integrations_secret_algorithm",
            ),
        ),
        migrations.AddConstraint(
            model_name="encryptedsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(("envelope_version", 1)),
                name="integrations_secret_envelope_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider__in", ["eventbrite", "groq", "iterable", "openai"])),
                name="integrations_connection_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ["not_configured", "configured", "healthy", "degraded", "disabled"],
                    )
                ),
                name="integrations_connection_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="integrations_connection_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationhealthcheck",
            constraint=models.CheckConstraint(
                condition=models.Q(("outcome__in", ["healthy", "degraded"])),
                name="integrations_health_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationhealthcheck",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_ms__gte", 0), ("duration_ms__lte", 30000)),
                name="integrations_health_duration_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationhealthcheck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("error_category", ""), ("outcome", "healthy")),
                    models.Q(
                        ("error_category__in", [
                            "authentication",
                            "authorization",
                            "rate_limit",
                            "timeout",
                            "network",
                            "invalid_response",
                            "provider_unavailable",
                        ]),
                        ("outcome", "degraded"),
                    ),
                    _connector="OR",
                ),
                name="integrations_health_safe_error_category",
            ),
        ),
    ]
