# Generated by Django 5.2.17 on 2026-10-10 04:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0009_hermes_worker_trace_context"),
        ("identity", "0002_security_event_append_only"),
        ("integrations", "0004_draft_execution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="draftexecution",
            name="provider_configuration",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="TemplateExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=16)),
                ("organization_id", models.CharField(max_length=40)),
                ("event_id", models.CharField(blank=True, max_length=40)),
                ("expected_readback_digest", models.CharField(blank=True, max_length=64)),
                ("provider_configuration", models.JSONField(default=dict)),
                ("payload", models.JSONField()),
                ("request_digest", models.CharField(max_length=64)),
                ("review_digest", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("executing", "Executing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("receipt", models.JSONField(null=True)),
                ("provider_id", models.CharField(blank=True, max_length=40)),
                ("error_category", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("claimed_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "approval_session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="identity.administratorsession",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.draftoperation"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="agents.agentrun"
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                (
                                    "pending",
                                    "approved",
                                    "executing",
                                    "succeeded",
                                    "failed",
                                    "unknown",
                                ),
                            )
                        ),
                        name="integrations_template_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("action__in", ("create", "update"))),
                        name="integrations_template_action",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("approval_session__isnull", True),
                                ("approved_at__isnull", True),
                                ("approver__isnull", True),
                                ("claimed_at__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                models.Q(("status", "pending"), _negated=True),
                                ("approval_session__isnull", False),
                                ("approved_at__isnull", False),
                                ("approver__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="integrations_template_approval_required",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                status__in=("pending", "approved"),
                                claimed_at__isnull=True,
                                completed_at__isnull=True,
                                receipt__isnull=True,
                                provider_id="",
                                error_category="",
                            )
                            | models.Q(
                                status="executing",
                                claimed_at__isnull=False,
                                completed_at__isnull=True,
                                receipt__isnull=True,
                                error_category="",
                            )
                            | models.Q(
                                status__in=("unknown", "failed"),
                                claimed_at__isnull=False,
                                completed_at__isnull=False,
                            )
                            | (
                                models.Q(
                                    status="succeeded",
                                    claimed_at__isnull=False,
                                    completed_at__isnull=False,
                                    receipt__isnull=False,
                                )
                                & ~models.Q(provider_id="")
                            )
                        ),
                        name="integrations_template_execution_lifecycle",
                    ),
                ],
            },
        ),
    ]
