# Generated by Django 5.2.16 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("launchloop", "0002_demoactor_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "specialist",
                    models.CharField(
                        choices=[
                            ("event_readiness", "Event Readiness"),
                            ("campaign_composer", "Campaign Composer"),
                            ("audience_policy", "Audience and Policy"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="launchloop.eventrevision"
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to="launchloop.workflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="launchloop.agentrun",
                    ),
                ),
            ],
            options={"ordering": ("sequence", "id")},
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.UniqueConstraint(
                fields=("workflow", "revision", "specialist"),
                name="launchloop_unique_agent_run_per_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("specialist__in", ["event_readiness", "campaign_composer", "audience_policy"])
                ),
                name="launchloop_known_agent_specialist",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentactivity",
            constraint=models.UniqueConstraint(
                fields=("agent_run", "sequence"), name="launchloop_unique_agent_activity_sequence"
            ),
        ),
    ]
