# Generated by Django 5.2.17 on 2026-08-31 14:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("launchloop", "0003_workflow_telemetry_traceparent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(default="eventbrite", editable=False, max_length=32)),
                ("provider_event_id", models.CharField(max_length=64)),
                ("available", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProviderEventSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=240)),
                ("status", models.CharField(max_length=24)),
                ("provider_changed_at", models.DateTimeField()),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="launchloop.providerevent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="providerevent",
            name="current_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_sources",
                to="launchloop.providereventsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="eventrevision",
            name="source_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_revisions",
                to="launchloop.providereventsnapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="providereventsnapshot",
            constraint=models.UniqueConstraint(
                fields=("source", "fingerprint"), name="launchloop_unique_provider_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerevent",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_event_id"), name="launchloop_unique_provider_event"
            ),
        ),
    ]
