# Generated by Django 5.2.17 on 2026-08-31 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("launchloop", "0004_providerevent_providereventsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerevent",
            name="local_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_sources",
                to="launchloop.event",
            ),
        ),
    ]
